import { z } from "zod";

import { storeReadSetSchema, writeTargetSchema } from "../resolver/contracts.js";

// ---------------------------------------------------------------------------
// v2.1.0-rc.1 P3 — Resolved bindings snapshot (P3→P4 dependency-chain link).
//
// CLI `install` / `sync` / `bind` pre-resolve the workspace binding's read-set +
// write-target via the StoreResolver and persist the result to
// `~/.fabric/state/bindings/<workspace_binding_id>_resolved.json`. P4 hooks then
// read this snapshot directly (no re-resolution, no store parsing) and degrade
// harmlessly when it is absent (roadmap gemini#1). The snapshot MUST equal what
// the resolver produces from the same inputs (the P3 consistency acceptance
// test).
// ---------------------------------------------------------------------------
export const resolvedBindingsSnapshotSchema = z
  .object({
    // Schema version of the snapshot document.
    version: z.literal(1),
    // The project this snapshot is bound to (S13).
    project_id: z.string().min(1),
    // The local runtime binding key. Defaults to project_id for standard repos;
    // worktrees may isolate state by setting fabric-config.workspace_binding_id.
    workspace_binding_id: z.string().min(1),
    // ISO-8601 generation timestamp (provenance / staleness signal for doctor).
    generated_at: z.string().min(1),
    // Pre-resolved read-set (required_stores ∪ implicit personal + warnings).
    read_set: storeReadSetSchema,
    // Pre-resolved active write target for non-personal scopes (null if none).
    write_target: writeTargetSchema.nullable(),
    // Pre-computed store-backed knowledge counts, snapshotted at write time.
    // PROVENANCE ONLY: these are store-global counts cached in a per-workspace
    // file, so they go stale whenever store content changes out-of-band (a `git
    // pull` in the store repo, a sync run from a *different* bound workspace,
    // etc.) — the snapshot is only regenerated by install/sync/store-ops in the
    // workspace that runs them (KT-PIT-0017). Hooks MUST NOT trust these numbers
    // for nudges; they recount live from `knowledge_store_dirs`. Retained for
    // doctor provenance + backward-compatible fallback when dirs are absent.
    knowledge_stats: z
      .object({
        pending_count: z.number().int().nonnegative(),
        canonical_count: z.number().int().nonnegative(),
        oldest_pending_mtime_ms: z.number().nonnegative().nullable(),
      })
      .strict()
      .optional(),
    // Resolved absolute store ROOT dirs the knowledge_stats were derived from.
    // STABLE across content sync — they only change when mounts/bindings change,
    // which DOES regenerate the snapshot. Hooks walk `<dir>/knowledge/<type>` +
    // `<dir>/knowledge/pending` LIVE off these roots so nudge counts are always
    // fresh regardless of how store content changed (the underseed / review-
    // backlog false-positive root cure; pairs with knowledge_stats above).
    knowledge_store_dirs: z.array(z.string().min(1)).optional(),
  })
  .strict();

export type ResolvedBindingsSnapshot = z.infer<typeof resolvedBindingsSnapshotSchema>;
